### ISSUE TITLE
state of the project

### ISSUE THREAD

**Issue by einSelbst** [cypress-io/generator-node-cypress#19]
Thank you for taking time to open a new issue. Please
answer a few questions to help us fix it faster.

## Is this a bug report or a feature request?

- [ ] bug report
- [ ] feature request
-> neither

Hey, interesting project! I was wondering what the state of it is given that the last release had been in 2018 but the last commit was just 7 days ago. Thanks!

**Comment by bahmutov** [comment]
We have not been using this to be honest. I think most of the times we create a new NPM project using `npm init -y`, add CI using [GitHub Actions](https://glebbahmutov.com/blog/trying-github-actions/) (or CircleCI), set up [Prettier](https://glebbahmutov.com/blog/configure-prettier-in-vscode/) and set up [Renovate](https://glebbahmutov.com/blog/renovate-app/) to keep dependencies up to date. So no "heavy" generators necessary.
