### ISSUE TITLE
Add renovate.json with defaults

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/generator-node-cypress#5]
Thank you for taking time to open a new issue. Please
answer a few questions to help us fix it faster.

## Is this a bug report or a feature request?

- [ ] bug report
- [x] feature request

If this is a bug report, please provide as much info as possible

- version
- platform
- expected behavior
- actual behavior

If this is a new feature request, please describe it below

**Comment by bahmutov** [comment]
Version `1.1.0` has been published to NPM. The full release note can be found at [generator-node-cypress/releases/tag/v1.1.0](https://github.com/cypress-io/generator-node-cypress/releases/tag/v1.1.0).

**Tip:** safely upgrade dependency generator-node-cypress in your project using [next-update](https://github.com/bahmutov/next-update)
